'use strict';
// tests for hilmatenders
// Generated by serverless-mocha-plugin

const mod         = require('../functions/hilmatenders/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

describe('hilmatenders', () => {
  before(function (done) {
    wrapper.init(mod);

    done()
  })
  
  it('implement tests here', (done) => {
    wrapper.init(mod);
    wrapper.run({}, (err, response) => {
      if (response.tenders.length > 0) {
        // Test the contents of one tender
        var testTender = response.tenders.pop();
        // Valid ID
        //console.log(testTender);
        expect(testTender.ID).to.match(/^[0-9]+-[0-9]+$/);
        // Valid name
        expect(testTender.name).to.match(/[^\s]+/);
        // Valid URL
        expect(testTender.url).to.match(/http.+/);
        // Valid Organization
        expect(testTender.organization).to.match(/[^\s]+/);
         // Tender type
        expect(testTender.ttype).to.match(/[^\s]+/);
        // Entry date type = Date
        //expect(testTender.entrydate).to.match(/(\d{4})-(\d{2})-(\d{2})T.+/);
      }
      done();
    });
  });
});
